### ISSUE TITLE
Include Recurrence Rules

### ISSUE THREAD

**Issue by youmustfight** [langovoi/gatsby-source-ical#3]
It'd be great to pull in recurrence rules for each data point! Right now I'm pulling in all events, but I'm not able to project outwards if an event repeats. Include the `rrule` property will probably do the trick rather than including a full list of recurrences.

**Comment by scnroy** [comment]
Heya! Question related to this issue:

I'm having some trouble getting up and running with recurring events. @youmustfight, any pointers? I'm thinking two queries, one for all future events and one for all recurring events, then combine the two? I've been looking at https://github.com/jakubroztocil/rrule. Curious how others are approaching this.

Do y'all think it'd make sense to document some examples? Happy to open a new issue and, once I wrap my head around it, contribute something to that end.

Thanks!
